### ISSUE TITLE
Integration of TLCC without go/plugins and cc2syscc calls 

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger-labs/fabric-private-chaincode#242]
Current code integrates TLCC as a systemchaincode using go plugins and ERCC calls TLCC via chaincode2chaincode calls.

We currently build TLCC using `go build -buildmode=plugin`. See [makefile](https://github.com/hyperledger-labs/fabric-private-chaincode/blob/master/tlcc/Makefile#L13)

TLCC is then hooked into the peer via `core.yaml`
```
chaincode:
    system:
        tlcc: enable

    systemPlugins:
        - enabled: true
        name: tlcc
        path: /path-to/fabric-private-chaincode/tlcc/tlcc.so
        invokableExternal: true
        invokableCC2CC: true
```

However, with Fabric 2.0 [release](https://github.com/hyperledger/fabric/releases/tag/v2.0.0) this is not supported anymore.

```
FAB-15285: Support for invoking system chaincodes from user chaincodes
has been removed.

System chaincodes, for example QSCC, are intended to be
invoked by a client rather than by a user chaincode. Invoking from a user
chaincode caused deadlocks in prior releases.
```

```
FAB-15343: System Chaincode Plugins have been removed.

As part of a general
move away from go plugins as an extension mechanism for Fabric, the ability to
add system chaincodes via go plugins has been removed. Users wishing to extend
Fabric with custom system chaincodes may rebuild the peer binary with the
system chaincode built into the binary. This system chaincode should then be
defined and initialized like any other user chaincode would be. This new model
is very similar to the plugin model (which required that the plugin to be built
at the same exact commit of Fabric), and addresses the significant shortcomings
around the lifecycle and validation of system chaincode transactions.
```
